<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Paperdown.Markdown</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="HtmlSanitizer" />
    <PackageReference Include="Markdig" />
    <ProjectReference Include="..\Paperdown.Core\Paperdown.Core.csproj" />
  </ItemGroup>
</Project>
