<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>Paperdown.Pdf</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2">
      <PrivateAssets>none</PrivateAssets>
    </PackageReference>
    <PackageReference Include="PdfPig" />
    <ProjectReference Include="..\Paperdown.Core\Paperdown.Core.csproj" />
    <ProjectReference Include="..\Paperdown.Rendering\Paperdown.Rendering.csproj" />
  </ItemGroup>
</Project>
